INSERT INTO SOCIO_TORCEDOR (ID_SOCIO, NOME_SOCIO, EMAIL, DATA_NASCIMENTO, TIME_CORACAO) VALUES (1, 'Thiago Lopes',	   'thiago@hotmail.com', TO_DATE('1989-10-01', 'YYYY-MM-DD'), 'Portuguesa');
INSERT INTO SOCIO_TORCEDOR (ID_SOCIO, NOME_SOCIO, EMAIL, DATA_NASCIMENTO, TIME_CORACAO) VALUES (2, 'Marcos Silva', 	   'marcos@hotmail.com', TO_DATE('1990-06-20', 'YYYY-MM-DD'), 'Guarani');
INSERT INTO SOCIO_TORCEDOR (ID_SOCIO, NOME_SOCIO, EMAIL, DATA_NASCIMENTO, TIME_CORACAO) VALUES (3, 'Manoel Pereira',   'manoel@hotmail.com', TO_DATE('1991-06-21', 'YYYY-MM-DD'), 'Ponte Preta');
INSERT INTO SOCIO_TORCEDOR (ID_SOCIO, NOME_SOCIO, EMAIL, DATA_NASCIMENTO, TIME_CORACAO) VALUES (4, 'Carlos Andrade',   'carlos@hotmail.com', TO_DATE('1989-03-26', 'YYYY-MM-DD'), 'Paulista');
INSERT INTO SOCIO_TORCEDOR (ID_SOCIO, NOME_SOCIO, EMAIL, DATA_NASCIMENTO, TIME_CORACAO) VALUES (5, 'Tomas Lima',       'tomas@hotmail.com', TO_DATE('1988-05-09', 'YYYY-MM-DD'), 'Madureira');
INSERT INTO SOCIO_TORCEDOR (ID_SOCIO, NOME_SOCIO, EMAIL, DATA_NASCIMENTO, TIME_CORACAO) VALUES (6, 'Roberto Farias',   'roberto@hotmail.com', TO_DATE('1992-06-11', 'YYYY-MM-DD'), 'Cabo Frio');
INSERT INTO SOCIO_TORCEDOR (ID_SOCIO, NOME_SOCIO, EMAIL, DATA_NASCIMENTO, TIME_CORACAO) VALUES (7, 'Claudio Medeiros', 'claudio@hotmail.com', TO_DATE('1980-06-13', 'YYYY-MM-DD'), 'Criciuma');

INSERT INTO TIMECORACAO (ID_TIMECORACAO, NOME) VALUES (1, 'Portuguesa');
INSERT INTO TIMECORACAO (ID_TIMECORACAO, NOME) VALUES (2, 'Guarani');
INSERT INTO TIMECORACAO (ID_TIMECORACAO, NOME) VALUES (3, 'Ponte Preta');
INSERT INTO TIMECORACAO (ID_TIMECORACAO, NOME) VALUES (4, 'Paulista');
INSERT INTO TIMECORACAO (ID_TIMECORACAO, NOME) VALUES (5, 'Madureira');
INSERT INTO TIMECORACAO (ID_TIMECORACAO, NOME) VALUES (6, 'Cabo Frio');
INSERT INTO TIMECORACAO (ID_TIMECORACAO, NOME) VALUES (7, 'Criciuma');